on: [push, pull_request_target]
name: Go Vulnerability Check
jobs:
  Security:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.3
    - name: Fetch Repository
      uses: actions/checkout@v3
    - name: Install Govulncheck
      run: |
          export GO111MODULE=on
          export PATH=${PATH}:`go env GOPATH`/bin
          go install golang.org/x/vuln/cmd/govulncheck@latest
          go get github.com/mattn/go-isatty@v0.0.14
    - name: Run Govulncheck
      run: "`go env GOPATH`/bin/govulncheck ./..."